DROP TABLE IF EXISTS `system`.`system_conf`;
CREATE TABLE `system`.`system_conf` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(40) NOT NULL COMMENT '配置名',
    `val` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '配置值',
    `desc` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '配置说明',
    `show` TINYINT NOT NULL DEFAULT 0 COMMENT '是否可显示',
    `edit` TINYINT NOT NULL DEFAULT 0 COMMENT '是否可编辑',
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE `idx_key` (`key`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COMMENT='系统全局配置';
